### ISSUE TITLE
Great, so where can we discuss this thing?

### ISSUE THREAD

**Issue by kwoot** [xerus2000/howtodo#1]
Great, so where can we discuss this thing?

- Can tasks have dependencies (end to start being the most popular)?
- Can we do time management?
- Can it have a server component?
- Can it be written in a popular and easy to use programming language? (more important than execution speed I think)
- And the Pandora's box of advanced features: Supporting hooks, timers/cron

**Comment by xeruf** [comment]
Here :)

1. Definitely, what do you mean with "end to start"?
2. I would prefer to use the existing offers over at [timewarrior](https://github.com/GothenburgBitFactory/timewarrior) - also relates to (5), if we support hooks, and maybe even use the same format as taskwarrior, this would be trivial.
3. and 4. Didn't think about that, my focus is on the workflow for now. I really like Kotlin.

I would hope to leverage existing software, so many task managers have already been written, but somehow they all lack. I want to put the focus on modularity and configurability - so a user-defined attribute should be able to do/contain almost anything a normal attribute does.

One project I am looking at is [tasklite](https://tasklite.org/) because it is nicely minimal. Maybe it can work to build a wrapper around such a core, integrate with something like timewarrior for time tracking etc. That way, if somebody gets annoyed with part of the project and maybe isn't comfortable with the language (my main problem with taskw and timew), they can only tackle a part instead of starting from scratch again.

**Comment by kwoot** [comment]
1 end2start: in project planning there is very often a dependency relation between tasks. So only when one task is ended another one can start. Like placing furniture has a dependency on the building a house task. (other dependencies can easily be thought of like start to end, start tot start, end to end)

Thanks for all the other answers!

**Comment by xeruf** [comment]
Added some plans: https://github.com/xerus2000/howtodo/blob/master/plans.md

Currently thinking of wrapping tasklite to save effort. The idea is to have two separate components, plumbing and porcelain (like git), where the plumbing (i.e. the underlying storage & processing mechanism) could be swapped out without requiring a full rewrite.

**Comment by xeruf** [comment]
Updated it again, ideas are shaping up. I enjoy giving this some time to evolve, coming back to it every few weeks with new thoughts. I hope I can start implementation within the next few weeks. @kwoot are you interested in collaborating then?

> end2start: in project planning there is very often a dependency relation between tasks. So only when one task is ended another one can start. Like placing furniture has a dependency on the building a house task. (other dependencies can easily be thought of like start to end, start tot start, end to end)

After looking into wikipedia about [task dependencies](https://www.wikiwand.com/en/Dependency_(project_management)#Standard_types_of_dependencies), I don't think a task manager needs to account for anything other than FS - FF and SS can be modeled with subtasks, while I can't imagine any case of SF in a personal to-do list.

**Comment by kwoot** [comment]
Agreed. F2S is the most used dependency.
